version: '3.5'

services:
  reports:
    build:
      context: .
    image: quip_reports
    container_name: quip-reports
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./wsi:/data/wsi
